# Generated by Django 4.1.7 on 2023-04-30 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0003_remove_userguess_question_result_quiz_userguess_quiz_and_more'),
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('courses', models.ManyToManyField(to='cbt_app.courses')),
                ('current_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.level')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.discipline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
