# Generated by Django 4.1.7 on 2023-05-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(null=True, upload_to='./static/profile', verbose_name='Profile Picture'),
        ),
    ]
