# Generated by Django 4.2.2 on 2023-06-29 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_studentprofile_profile_date_of_birth_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth1.profile')),
            ],
            bases=('auth1.profile',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 14, 52, 5, 603530)),
        ),
    ]
