# Generated by Django 4.2.2 on 2023-06-29 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0005_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 13, 58, 13, 667123, tzinfo=datetime.timezone.utc)),
        ),
    ]
