# Generated by Django 4.2.2 on 2023-06-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0006_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
