# Generated by Django 4.1.7 on 2023-04-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.level'),
        ),
    ]
