# Generated by Django 4.1.7 on 2023-04-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbt_app.choice')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question')),
            ],
        ),
    ]
