# Generated by Django 4.2.2 on 2023-06-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0002_quiz_examiner_quiz_is_active_result_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_active',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
