# Generated by Django 4.2.2 on 2023-06-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0002_quiz_examiner_quiz_is_active_result_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='is_active',
            new_name='is_open',
        ),
    ]
