# Generated by Django 4.2.2 on 2023-06-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0003_rename_is_active_quiz_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_open',
        ),
    ]
