# Generated by Django 4.2.2 on 2023-06-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0003_remove_quiz_is_active_quiz_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload_title',
            field=models.CharField(default='no title', max_length=255, null=True),
        ),
    ]
