# Generated by Django 4.1.7 on 2023-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0003_remove_userguess_question_result_quiz_userguess_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(default=1, help_text='Display the questions in a random order or as they are set?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=True, help_text='orders with which questions will appear'),
        ),
    ]
