# Generated by Django 4.1.7 on 2023-04-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0003_alter_quiz_course_alter_quiz_examiner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(blank=True, choices=[], max_length=255),
        ),
    ]
