# Generated by Django 4.1.7 on 2023-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, choices=[('False', None), (False, models.TextField()), (False, models.TextField()), (True, models.TextField())], max_length=255),
        ),
    ]
