# Generated by Django 4.2.2 on 2023-06-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0004_question_upload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='duration',
            field=models.IntegerField(default=0, help_text='duration in minutes'),
            preserve_default=False,
        ),
    ]
