# Generated by Django 4.2.2 on 2023-06-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0005_sitting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.FloatField(default=0, help_text='duration in minutes'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='duration',
            field=models.FloatField(default=0, help_text='duration in minutes'),
        ),
    ]
