# Generated by Django 4.1.7 on 2023-05-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0005_sitting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='question_choice_pair',
            field=models.JSONField(blank=True, default=dict, help_text='json format question choice pair'),
        ),
    ]
