# Generated by Django 4.1.7 on 2023-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0006_alter_sitting_question_choice_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitting',
            name='is_attempted',
        ),
        migrations.AddField(
            model_name='sitting',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
    ]
