# Generated by Django 4.2.2 on 2023-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0007_uploadtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='upload_title',
        ),
        migrations.AddField(
            model_name='question',
            name='upload_title',
            field=models.ManyToManyField(to='cbt_app.uploadtitle'),
        ),
    ]
