# Generated by Django 4.1.7 on 2023-05-07 16:37

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0007_remove_sitting_is_attempted_sitting_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitting',
            name='question_attempted',
            field=models.CharField(default=0, max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Answered Questions'),
            preserve_default=False,
        ),
    ]
