# Generated by Django 4.1.7 on 2023-04-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0007_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='opt1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question')),
            ],
        ),
    ]
