# Generated by Django 4.1.7 on 2023-04-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0008_remove_question_opt1_remove_question_opt2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='answer',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quest_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option3',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('random', 'Random'), ('none', 'None')], help_text='The order in which multichoice answer options are displayed to the user', max_length=30, null=True),
        ),
    ]
