# Generated by Django 4.1.7 on 2023-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0008_sitting_end_time_sitting_question_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
    ]
