# Generated by Django 4.2.2 on 2023-06-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0009_alter_quiz_course_alter_quiz_examiner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='time_left',
            field=models.FloatField(default=0, help_text='duration in minutes'),
        ),
    ]
