# Generated by Django 4.1.7 on 2023-05-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0010_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(to='cbt_app.topic'),
        ),
    ]
