# Generated by Django 4.1.7 on 2023-05-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0011_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbt_app.courses'),
        ),
    ]
