# Generated by Django 4.2.2 on 2023-06-19 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuploads',
            name='upload',
            field=models.FileField(default=1, upload_to='./static/uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv'])], verbose_name='Excel file'),
            preserve_default=False,
        ),
    ]
