# Generated by Django 4.1.7 on 2023-05-19 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuploads',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='./static/uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv'])], verbose_name='Excel file'),
        ),
    ]
