# Generated by Django 4.1.7 on 2023-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0002_alter_questionuploads_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuploads',
            name='file',
            field=models.FileField(upload_to='./static/uploads', verbose_name='Excel file'),
        ),
    ]
